### ISSUE TITLE
MaterialSkin issue.

### ISSUE THREAD

**Issue by ScaredDonut** [serialtasted/arma3Launcher#19]
Hi there,

I am trying to compile this resource, however, I am stuck because for some reason the MaterialSkin package seems to be broken or something. There are 193 errors, when I try to compile. 

Here is a pastebin: https://pastebin.com/YgAxSFJ6

My NuGet packages: https://imgdash.com/images/2020/05/05/nugetpackages7841a19a43bc334b.png

Thanks for your time and help!

**Comment by serialtasted** [comment]
The MaterialSkin.dll that I'm using is not the one from Ignace Maes. It's is based on it but with some other things. I can't seem to find the page or author of it but I do have the dll. I might change it in the future to one that's present on the nuget manager but for the time I'll keep using this one because it's the only one that has the snackbar control.

Feel free to run it by https://www.jetbrains.com/decompiler/ and see what's inside of it. I'm sorry I couldn't help you more. If you want to use this just download the zip file attached, in there there's the .dll for the correct MaterialSkin library that this project uses. And you just need to add it to the references in the project.

[MaterialSkin.zip](https://github.com/serialtasted/arma3Launcher/files/4583500/MaterialSkin.zip)

**Comment by serialtasted** [comment]
There's another version from leocb (https://github.com/leocb/MaterialSkin https://www.nuget.org/packages/MaterialSkin.2/) but without the snackbar and with some differences in the code but also based on the version from Ignace. If you want to use this one beware that you will need to make a few changes to the code to get it to work.

**Comment by ScaredDonut** [comment]
Cheers! Thanks for your assistance. :).

**Comment by serialtasted** [comment]
I'm gonna leave this open, please close it if this problem as been solved. If you need any more help feel free to ask!
